site_name: 技术传播百态说
theme:
  name: material
  language: zh
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: custom
      accent: custom

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: custom
      accent: custom
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.path
    - navigation.footer
    - toc.follow
  custom_dir: overrides

extra_css:
  - stylesheets/palette.css
  - stylesheets/page.css
  - stylesheets/nav.css

extra:
  homepage: https://www.docsimpo.work/
  doc_title: "Markdown 语法中心"

nav:
  - 基本语法:
    - basic/index.md
    - basic/headings.md
    - basic/paragraph.md
    - basic/newline.md
    - basic/emphasis.md
    - basic/blockquote.md
    - basic/list.md
    - basic/link.md
    - basic/image.md
    - basic/code.md
    - basic/code-block.md
    - basic/horizontal-rules.md
    - basic/backslash-escapes.md
    - basic/html.md
  - 扩展语法:
    - extended/index.md
    - extended/table.md
    - extended/fenced-code-block.md
    - extended/footnote.md
    - extended/definition-list.md
    - extended/task-list.md
    - extended/heading-with-id.md
    - extended/strikethrough.md
    - extended/automatic-url-link.md
    - extended/Emoji.md
  - kramdown 语法:
    - kramdown/index.md
    - kramdown/abbreviation.md
    - kramdown/block-attribute.md
    - kramdown/inline-attribute.md
    - kramdown/built-in-attributes.md
    - kramdown/extension-comment.md
    - kramdown/extension-nomarkdown.md
    - kramdown/extension-options.md
    - kramdown/option-list.md
  - pandoc 语法:
    - pandoc/index.md
    - pandoc/line-block.md
    - pandoc/sup-and-sub.md
    - pandoc/divs.md
    - pandoc/spans.md
    - pandoc/metadata-block.md
    - pandoc/newline.md
    - pandoc/citation.md


markdown_extensions:
  - nl2br
  - abbr
  - footnotes
  - def_list
  - attr_list
  - admonition
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
      auto_title: true
  - pymdownx.blocks.html
  - pymdownx.snippets:
      base_path: snippets

