site_name: Markdown Syntax Hub
theme:
  name: material
  language: zh
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.path
    - toc.follow
  custom_dir: overrides

nav:
  - index.md
  - 基本语法:
    - basic/index.md
    - basic/headings.md
    - basic/paragraph.md
    - basic/newline.md
    - basic/emphasis.md
    - basic/blockquote.md
    - basic/list.md
    - basic/link.md
    - basic/image.md
    - basic/code.md
    - basic/code-block.md
    - basic/horizontal-rules.md
    - basic/backslash-escapes.md
    - basic/html.md
  - 扩展语法:
    - extended/index.md
    - extended/table.md
    - extended/fenced-code-block.md
    - extended/footnote.md
    - extended/definition-list.md
    - extended/task-list.md
    - extended/heading-with-id.md
    - extended/strikethrough.md
    - extended/automatic-url-link.md
    - extended/Emoji.md
  - kramdown 语法:
    - kramdown/index.md
    - kramdown/abbreviation.md
    - kramdown/block-attribute.md
    - kramdown/inline-attribute.md
    - kramdown/built-in-attributes.md
    - kramdown/extension-comment.md
    - kramdown/extension-nomarkdown.md
    - kramdown/extension-options.md
    - kramdown/option-list.md
  - pandoc 语法:
    - pandoc/index.md
    - pandoc/line-block.md
    - pandoc/sup-and-sub.md
    - pandoc/divs.md
    - pandoc/spans.md
    - pandoc/metadata-block.md
    - pandoc/newline.md
    - pandoc/citation.md


markdown_extensions:
  - nl2br
  - abbr
  - footnotes
  - def_list
  - attr_list
  - admonition
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
      auto_title: true
  - pymdownx.blocks.html
  - pymdownx.snippets:
      base_path: snippets

extra_css:
  - stylesheets/page.css